### PR TITLE
feat: switch cdn to netlify

### LINKED ISSUE #5: [CHORE] - Switch cdn subdomain to Netlify
### What work needs to be performed?

Change the A record to a CNAME, pointing to chipper-druid-7fcb90.netlify.app

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by taciturnaxolotl**
# Switch CDN to Netlify
## Description:

Changed the A record to a CNAME pointing to chipper-druid-7fcb90.netlify.app.

## Related Issue:
Closes #5

### CODE REVIEW

**Review by reesericci — CHANGES_REQUESTED** [review]
add it as an addition, not a replacement

**Comment by taciturnaxolotl** [comment]
I think I added it but octodns seems to be failing repeatedly

**Comment by jaspermayone** [comment]
It can't connect to the local bind because the local server is still down. I am working on getting that back up, but proxmox is being VERY stubborn

**Review by jaspermayone — CHANGES_REQUESTED** [review]
@kcoderhtml as DNS changes are critical, I have the workspace colored red

**Comment by taciturnaxolotl** [comment]
Reverted the color changes! I had assumed that it was accidental

**Review by jaspermayone — APPROVED** [review]

**Comment by jaspermayone** [comment]
I will rerun the DNS deploy manually 1 sec

**Pull request merged**
